name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        cd boa-learn
        pipenv install --dev

    - name: Check Formatting
      run: |
        cd boa-learn
        pipenv run black --check

    - name: Test with pytest
      run: |
        cd boa-learn
        pipenv run pytest